### ISSUE TITLE
Missing config folder

### ISSUE THREAD

**Issue by pgierz** [pgierz/esm-viz#17]
Chris reports that there is no config folder present by default.

**Comment by pgierz** [comment]
@chrisdane, please try the branch `generate_config_dir`. There will be likely be problems afterward. For a development install, clone it, checkout whatever branch you want, and then do the `pip install --user .` in the directory.

**Comment by chrisdane** [comment]
```
$ git status
On branch generate_config_dir
Your branch is up-to-date with 'origin/generate_config_dir'.
nothing to commit, working directory clean

$ pip install --user .
...
Successfully installed esm-viz-0.9.1

$ ls ~/.config/monitoring
ls: cannot access '/home/csys/cdanek/.config/monitoring': No such file or directory
```

**Comment by pgierz** [comment]
The install doesn't set up the config folder for you, running the following might:

```
$ esm_viz --expid something
```

You still need to give a valid yaml file as something, there is an example in the top of the repo.

**Comment by chrisdane** [comment]
```
$ ls *.yaml
example.yaml

$ esm_viz --expid example
Scheduling...
Successfully scheduled automatic monitoring of example every 2 hours
Deploying...
Traceback (most recent call last):
  File "/home/csys/cdanek/.local/bin/esm_viz", line 11, in <module>
    load_entry_point('esm-viz==0.9.1', 'console_scripts', 'esm_viz')()
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/esm_viz/cli.py", line 42, in main
    ctx.invoke(deploy, expid=expid, quiet=quiet)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/esm_viz/cli.py", line 107, in deploy
    config = read_simulation_config(expid)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/esm_viz/esm_viz.py", line 25, in read_simulation_config
    config_dir = os.environ.get("HOME") + "/.config/monitoring/"
NameError: global name 'os' is not defined

$ ls ~/.local/monitoring
ls: cannot access '/home/csys/cdanek/.local/monitoring': No such file or directory

**Comment by pgierz** [comment]
Just pushed, try again

**Comment by pgierz** [comment]
and, out of curiosity, what does your crontab look like now?

**Comment by chrisdane** [comment]
```
$ esm_viz --expid example
Scheduling...
Successfully scheduled automatic monitoring of example every 2 hours
Deploying...
Traceback (most recent call last):
  File "/home/csys/cdanek/.local/bin/esm_viz", line 11, in <module>
    load_entry_point('esm-viz==0.9.1', 'console_scripts', 'esm_viz')()
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/esm_viz/cli.py", line 42, in main
    ctx.invoke(deploy, expid=expid, quiet=quiet)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/esm_viz/cli.py", line 107, in deploy
    config = read_simulation_config(expid)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/esm_viz/esm_viz.py", line 38, in read_simulation_config
    with open(config_file) as cfg:
IOError: [Errno 2] No such file or directory: u'example'
```

**Comment by chrisdane** [comment]
```
$ esm_viz --expid example
Scheduling...
Successfully scheduled automatic monitoring of example every 2 hours
Deploying...
example
example.yaml
Copying file to config folder
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_5.3)
INFO:paramiko.transport:Authentication (publickey) failed.
ERROR:root:Hey, you can't log on to this computer: mistral.dkrz.de. Set up your keys!!! See also the error message in your home folder!
```

=)
