### ISSUE TITLE
branch py2py3_fileerror: esm_viz combine --expid=example

### ISSUE THREAD

**Issue by chrisdane** [pgierz/esm-viz#25]
At branch: py2py3_fileerror
```
$ esm_viz combine --expid=example
['/home/csys/cdanek/.local/lib/python2.7/site-packages/esm_viz/visualization/read_config.ipynb', '/home/csys/cdanek/.local/lib/python2.7/site-packages/esm_viz/visualization/echam_global_timeseries.ipynb', '/home/csys/cdanek/.local/lib/python2.7/site-packages/esm_viz/visualization/echam_global_climatology.ipynb', '/home/csys/cdanek/.local/lib/python2.7/site-packages/esm_viz/visualization//last_update.ipynb']
Combined notebook; executing and converting to HTML
Traceback (most recent call last):
  File "/home/csys/cdanek/.local/bin/esm_viz", line 11, in <module>
    load_entry_point('esm-viz==0.9.5', 'console_scripts', 'esm_viz')()
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/esm_viz/cli.py", line 298, in combine
    ep.preprocess(nb, {"metadata": {"path": "./"}})
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 403, in preprocess
    with self.setup_preprocessor(nb, resources, km=km):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 345, in setup_preprocessor
    self.km, self.kc = self.start_new_kernel(**kwargs)
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 287, in start_new_kernel
    km = self.kernel_manager_class(kernel_name=self.kernel_name,
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/home/csys/cdanek/.local/lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 251, in _kernel_manager_class_default
    raise ImportError("`nbconvert --execute` requires the jupyter_client package: `pip install jupyter_client`")
ImportError: `nbconvert --execute` requires the jupyter_client package: `pip install jupyter_client`
```

**Comment by pgierz** [comment]
Note for Paul: Problem with `requirements.txt`. Apparently we need `jupyter_client`.

**Comment by pgierz** [comment]
Probably we can close this once everything gets moved to py2/py3 agnostic panel stuff.
